#!/bin/sh

alias xrem='sudo xbps-remove -o'

xque () {
   xbps-query -Rs "" \
      | fzf -q "$*" \
      | gawk '{print $2}' \
      | xargs -ro sudo xbps-install
}


xs () {
   xpkg -a |
      fzf -m --preview 'xq {1}'  \
      --preview-window=right:66%:wrap |
      xargs -ro xi
}

alias ,todo='vim ~/Markor/todo.txt'
alias ,ta='tmux attach'
alias ,mpvmusic='mpv --no-video'
alias ,fixtime='sudo vsv stop ntpd; sudo ntpdate 216.239.35.0'
alias ,change_layout='setxkbmap -model 104 -layout us,ara -option grp:alt_caps_toggle'
