#!/bin/sh

alias xrem='sudo xbps-remove -o'

xque () {
   xbps-query -Rs "" \
      | fzf -q "$*" \
      | gawk '{print $2}' \
      | xargs -ro sudo xbps-install
}


xs () {
   xpkg -a |
      fzf -m --preview 'xq {1}'  \
      --preview-window=right:66%:wrap |
      xargs -ro xi
}

alias todo='vim ~/Markor/todo.txt'
